language: android
android:
 components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository  
    

jdk: oraclejdk8

script:
    - chmod +x gradlew
    - ./gradlew testDebug
